from pathlib import Path
import os
GEN_FILE_PATH = "src/utility/ImageNames.hpp"

IMAGE_PATH = 'resources/images'
IMAGE_REGEX = '*.png'

def write_file_start(toGen):
    toGen.write("#pragma once\n")
    toGen.write("\n")
    toGen.write("//File generated by the gen_img.py script\n")
    toGen.write("\n")
    toGen.write("namespace image {\n")

def traverse_directory(path, toGen):
    folder = Path(path)
    for item in folder.iterdir():
        if item.is_dir():
            toGen.write(f"namespace {item.name}{{")
            traverse_directory(item, toGen)
            toGen.write(f"}}")
        elif item.is_file() and item.suffix == ".png":
            file_name = item.name
            cpp_var_name = item.stem.upper()
            toGen.write(f"  constexpr char {cpp_var_name}[] = \"{file_name}\";\n")

def append_file_contents(toGen):
    for img_path in Path(IMAGE_PATH).rglob(IMAGE_REGEX):
        img_name = img_path.name
        cpp_var_name = img_path.stem.upper()
        toGen.write(f"  constexpr char {cpp_var_name}[] = \"{img_name}\";\n")

def write_file_end(toGen):
    toGen.write("} // namespace image")
    toGen.write("\n")

def main():
    with open(GEN_FILE_PATH, "w") as toGen:
        write_file_start(toGen)
        #append_file_contents(toGen)
        traverse_directory(IMAGE_PATH, toGen)
        write_file_end(toGen)

if __name__ == "__main__":
    main()
    #traverse_directory(IMAGE_PATH, "a")
