from pathlib import Path

GEN_FILE_PATH = "src/utility/ImageNames.hpp"

IMAGE_PATH = 'resources/images'
IMAGE_REGEX = '*.png'

def write_file_start(toGen):
    toGen.write("#pragma once\n")
    toGen.write("\n")
    toGen.write("//File generated by the gen_img.py script\n")
    toGen.write("\n")
    toGen.write("namespace Item {\n")

def append_file_contents(toGen):
    for img_path in Path(IMAGE_PATH).rglob(IMAGE_REGEX):
        img_name = img_path.name
        cpp_var_name = img_path.stem.upper()
        toGen.write(f"  constexpr char {cpp_var_name}[] = \"{img_name}\";\n")

def write_file_end(toGen):
    toGen.write("} // namespace Item")
    toGen.write("\n")

def main():
    with open(GEN_FILE_PATH, "w") as toGen:
        write_file_start(toGen)
        append_file_contents(toGen)
        write_file_end(toGen)

if __name__ == "__main__":
    main()
