#pragma once

// File generated by the gen_img.py script

namespace image {
  namespace backgrounds {
    constexpr char OUTPUT_SMALL[] = "output_small.png";
    constexpr char OUTPUT[] = "output.png";
  }  // namespace backgrounds
  namespace spells {
    namespace summoning {
      constexpr char SUMMON_SCORPIONS[] = "summon_scorpions.png";
      constexpr char SUMMON_SHADOW_CREATURES[] = "summon_shadow_creatures.png";
      constexpr char SUMMON_BUTTERFLIES[] = "summon_butterflies.png";
      constexpr char SUMMON_UGLY_THING[] = "summon_ugly_thing.png";
      constexpr char SUMMON_DEMON[] = "summon_demon.png";
      constexpr char SUMMON_ICE_BEAST[] = "summon_ice_beast.png";
      constexpr char CALL_CANINE_FAMILIAR[] = "call_canine_familiar.png";
      constexpr char RECALL[] = "recall.png";
      constexpr char SUMMON_ELEMENTAL[] = "summon_elemental.png";
      constexpr char SUMMON_HORRIBLE_THINGS[] = "summon_horrible_things.png";
      constexpr char SUMMON_SMALL_MAMMALS[] = "summon_small_mammals.png";
      constexpr char STICKS_TO_SNAKES[] = "sticks_to_snakes.png";
      constexpr char CALL_IMP[] = "call_imp.png";
      constexpr char ABJURATION[] = "abjuration.png";
      constexpr char SUMMON_GREATER_DEMON[] = "summon_greater_demon.png";
      constexpr char DEMONIC_HORDE[] = "demonic_horde.png";
    }  // namespace summoning
    namespace conjuration {
      constexpr char ORB_OF_DESTRUCTION[] = "orb_of_destruction.png";
      constexpr char ISKENDERUNS_MYSTIC_BLAST[] = "iskenderuns_mystic_blast.png";
      constexpr char MAGIC_DART[] = "magic_dart.png";
    }  // namespace conjuration
    namespace ice {
      constexpr char FREEZE[] = "freeze.png";
      constexpr char ENSORCELLED_HIBERNATION[] = "ensorcelled_hibernation.png";
      constexpr char CONDENSATION_SHIELD[] = "condensation_shield.png";
      constexpr char OZOCUBUS_ARMOUR[] = "ozocubus_armour.png";
      constexpr char THROW_FROST[] = "throw_frost.png";
      constexpr char ICE_FORM[] = "ice_form.png";
      constexpr char FREEZING_CLOUD[] = "freezing_cloud.png";
      constexpr char THROW_ICICLE[] = "throw_icicle.png";
      constexpr char METABOLIC_ENGLACIATION[] = "metabolic_englaciation.png";
      constexpr char FREEZING_AURA[] = "freezing_aura.png";
      constexpr char OZOCUBUS_REFRIGERATION[] = "ozocubus_refrigeration.png";
      constexpr char BOLT_OF_COLD[] = "bolt_of_cold.png";
      constexpr char ICE_STORM[] = "ice_storm.png";
    }  // namespace ice
    namespace necromancy {
      constexpr char BONE_SHARDS[] = "bone_shards.png";
      constexpr char SYMBOL_OF_TORMENT[] = "symbol_of_torment.png";
      constexpr char ANIMATE_DEAD[] = "animate_dead.png";
      constexpr char LETHAL_INFUSION[] = "lethal_infusion.png";
      constexpr char ANIMATE_SKELETON[] = "animate_skeleton.png";
      constexpr char SUBLIMATION_OF_BLOOD[] = "sublimation_of_blood.png";
      constexpr char NECROMUTATION[] = "necromutation.png";
      constexpr char DEATH_CHANNEL[] = "death_channel.png";
      constexpr char BOLT_OF_DRAINING[] = "bolt_of_draining.png";
      constexpr char VAMPIRIC_DRAINING[] = "vampiric_draining.png";
      constexpr char REGENERATION[] = "regeneration.png";
      constexpr char BORGNJORS_REVIVIFICATION[] = "borgnjors_revivification.png";
      constexpr char CIGOTUVIS_DEGENERATION[] = "cigotuvis_degeneration.png";
      constexpr char DISPEL_UNDEAD[] = "dispel_undead.png";
      constexpr char DEATHS_DOOR[] = "deaths_door.png";
      constexpr char PAIN[] = "pain.png";
      constexpr char FULSOME_DISTILLATION[] = "fulsome_distillation.png";
      constexpr char SIMULACRUM[] = "simulacrum.png";
      constexpr char EXCRUCIATING_WOUNDS[] = "excruciating_wounds.png";
      constexpr char HAUNT[] = "haunt.png";
      constexpr char CONTROL_UNDEAD[] = "control_undead.png";
      constexpr char AGONY[] = "agony.png";
      constexpr char TWISTED_RESURRECTION[] = "twisted_resurrection.png";
      constexpr char CORPSE_ROT[] = "corpse_rot.png";
    }  // namespace necromancy
    namespace air {
      constexpr char CHAIN_LIGHTNING[] = "chain_lightning.png";
      constexpr char STATIC_DISCHARGE[] = "static_discharge.png";
      constexpr char CONJURE_BALL_LIGHTNING[] = "conjure_ball_lightning.png";
      constexpr char AIRSTRIKE[] = "airstrike.png";
      constexpr char LIGHTNING_BOLT[] = "lightning_bolt.png";
      constexpr char SHOCK[] = "shock.png";
      constexpr char LEVITATION[] = "levitation.png";
      constexpr char INSULATION[] = "insulation.png";
      constexpr char SWIFTNESS[] = "swiftness.png";
      constexpr char FLIGHT[] = "flight.png";
      constexpr char DEFLECT_MISSILES[] = "deflect_missiles.png";
      constexpr char SILENCE[] = "silence.png";
      constexpr char REPEL_MISSILES[] = "repel_missiles.png";
    }  // namespace air
    namespace earth {
      constexpr char SHATTER[] = "shatter.png";
      constexpr char LEHUDIBS_CRYSTAL_SPEAR[] = "lehudibs_crystal_spear.png";
      constexpr char STATUE_FORM[] = "statue_form.png";
      constexpr char MAXWELLS_SILVER_HAMMER[] = "maxwells_silver_hammer.png";
      constexpr char DIG[] = "dig.png";
      constexpr char STONESKIN[] = "stoneskin.png";
      constexpr char IRON_SHOT[] = "iron_shot.png";
      constexpr char SANDBLAST[] = "sandblast.png";
      constexpr char PASSWALL[] = "passwall.png";
      constexpr char LEES_RAPID_DECONSTRUCTION[] = "lees_rapid_deconstruction.png";
      constexpr char STONE_ARROW[] = "stone_arrow.png";
    }  // namespace earth
    namespace transmutation {
      constexpr char BLADE_HANDS[] = "blade_hands.png";
      constexpr char ALTER_SELF[] = "alter_self.png";
      constexpr char POLYMORPH_OTHER[] = "polymorph_other.png";
    }  // namespace transmutation
    namespace disciplines {
      constexpr char SUMMONING[] = "summoning.png";
      constexpr char NECROMANCY[] = "necromancy.png";
      constexpr char AIR[] = "air.png";
      constexpr char DIVINATION[] = "divination.png";
      constexpr char TRANSMUTATION[] = "transmutation.png";
      constexpr char POISON[] = "poison.png";
      constexpr char FIRE[] = "fire.png";
      constexpr char EARTH[] = "earth.png";
      constexpr char ICE[] = "ice.png";
      constexpr char CONJURATION[] = "conjuration.png";
      constexpr char ENCHANTMENT[] = "enchantment.png";
      constexpr char TRANSLOCATION[] = "translocation.png";
    }  // namespace disciplines
    constexpr char MEMORISE[] = "memorise.png";
    namespace divination {
      constexpr char DETECT_TRAPS[] = "detect_traps.png";
      constexpr char DETECT_SECRET_DOORS[] = "detect_secret_doors.png";
      constexpr char DETECT_ITEMS[] = "detect_items.png";
      constexpr char DETECT_CREATURES[] = "detect_creatures.png";
    }  // namespace divination
    namespace translocation {
      constexpr char BLINK[] = "blink.png";
      constexpr char CONTROLLED_BLINK[] = "controlled_blink.png";
      constexpr char BANISHMENT[] = "banishment.png";
      constexpr char DISPERSAL[] = "dispersal.png";
      constexpr char PHASE_SHIFT[] = "phase_shift.png";
      constexpr char TELEPORT[] = "teleport.png";
      constexpr char WARP_WEAPON[] = "warp_weapon.png";
      constexpr char APPORTATION[] = "apportation.png";
      constexpr char CONTROLLED_TELEPORT[] = "controlled_teleport.png";
      constexpr char TELEPORT_OTHER[] = "teleport_other.png";
      constexpr char PORTAL_PROJECTILE[] = "portal_projectile.png";
      constexpr char PORTAL[] = "portal.png";
    }  // namespace translocation
    namespace fire {
      constexpr char FLAME_TONGUE[] = "flame_tongue.png";
      constexpr char THROW_FLAME[] = "throw_flame.png";
      constexpr char FIREBALL[] = "fireball.png";
      constexpr char IGNITE_POISON[] = "ignite_poison.png";
      constexpr char STICKY_FLAME[] = "sticky_flame.png";
      constexpr char CONJURE_FLAME[] = "conjure_flame.png";
      constexpr char FIRE_BRAND[] = "fire_brand.png";
      constexpr char EVAPORATE[] = "evaporate.png";
      constexpr char FIRE_STORM[] = "fire_storm.png";
      constexpr char DRAGON_FORM[] = "dragon_form.png";
      constexpr char DELAYED_FIREBALL[] = "delayed_fireball.png";
      constexpr char RING_OF_FLAMES[] = "ring_of_flames.png";
      constexpr char BOLT_OF_MAGMA[] = "bolt_of_magma.png";
      constexpr char BOLT_OF_FIRE[] = "bolt_of_fire.png";
    }  // namespace fire
    namespace enchantment {
      constexpr char MASS_CONFUSION[] = "mass_confusion.png";
      constexpr char CAUSE_FEAR[] = "cause_fear.png";
      constexpr char TAME_BEASTS[] = "tame_beasts.png";
      constexpr char HASTE[] = "haste.png";
      constexpr char CORONA[] = "corona.png";
      constexpr char INVISIBILITY[] = "invisibility.png";
      constexpr char SELECTIVE_AMNESIA[] = "selective_amnesia.png";
      constexpr char CONFUSE[] = "confuse.png";
      constexpr char EXTENSION[] = "extension.png";
      constexpr char SLOW[] = "slow.png";
      constexpr char TUKIMAS_DANCE[] = "tukimas_dance.png";
      constexpr char CONFUSING_TOUCH[] = "confusing_touch.png";
      constexpr char SURE_BLADE[] = "sure_blade.png";
      constexpr char PROJECTED_NOISE[] = "projected_noise.png";
      constexpr char TUKIMAS_VORPAL_BLADE[] = "tukimas_vorpal_blade.png";
      constexpr char SEE_INVISIBLE[] = "see_invisible.png";
      constexpr char ENSLAVEMENT[] = "enslavement.png";
      constexpr char BERSERKER_RAGE[] = "berserker_rage.png";
      constexpr char PETRIFY[] = "petrify.png";
    }  // namespace enchantment
    namespace poison {
      constexpr char STING[] = "sting.png";
      constexpr char VENOM_BOLT[] = "venom_bolt.png";
      constexpr char OLGREBS_TOXIC_RADIANCE[] = "olgrebs_toxic_radiance.png";
      constexpr char RESIST_POISON[] = "resist_poison.png";
      constexpr char POISON_ARROW[] = "poison_arrow.png";
      constexpr char POISON_BRAND[] = "poison_brand.png";
      constexpr char MEPHITIC_CLOUD[] = "mephitic_cloud.png";
      constexpr char SPIDER_FORM[] = "spider_form.png";
      constexpr char POISONOUS_CLOUD[] = "poisonous_cloud.png";
      constexpr char ALISTAIRS_INTOXICATION[] = "alistairs_intoxication.png";
      constexpr char CURE_POISON[] = "cure_poison.png";
    }  // namespace poison
  }    // namespace spells
  namespace monsters {
    constexpr char ETTIN[] = "ettin.png";
    constexpr char HELL_KNIGHT[] = "hell_knight.png";
    constexpr char BOGGART[] = "boggart.png";
    constexpr char NAGA_WARRIOR[] = "naga_warrior.png";
    constexpr char YAKTAUR_CAPTAIN[] = "yaktaur_captain.png";
    constexpr char CENTAUR_WARRIOR[] = "centaur_warrior.png";
    constexpr char HUMAN[] = "human.png";
    constexpr char MERFOLK_PLAIN_WATER[] = "merfolk_plain_water.png";
    constexpr char ORC_SORCERER[] = "orc_sorcerer.png";
    constexpr char ROCK_TROLL_MONK_GHOST[] = "rock_troll_monk_ghost.png";
    constexpr char IRON_DRAGON[] = "iron_dragon.png";
    constexpr char HYDRA2[] = "hydra2.png";
    constexpr char KILLER_KLOWN[] = "killer_klown.png";
    constexpr char DEEP_ELF_ANNIHILATOR[] = "deep_elf_annihilator.png";
    constexpr char HIPPOGRIFF[] = "hippogriff.png";
    constexpr char DEEP_ELF_DEMONOLOGIST[] = "deep_elf_demonologist.png";
    constexpr char DEEP_ELF_KNIGHT[] = "deep_elf_knight.png";
    constexpr char MERFOLK_FIGHTER_WATER[] = "merfolk_fighter_water.png";
    constexpr char DEMONSPAWN[] = "demonspawn.png";
    constexpr char DEEP_ELF_HIGH_PRIEST[] = "deep_elf_high_priest.png";
    constexpr char MERMAID_WATER[] = "mermaid_water.png";
    constexpr char ICE_BEAST[] = "ice_beast.png";
    constexpr char DEEP_ELF_SOLDIER[] = "deep_elf_soldier.png";
    constexpr char TITAN[] = "titan.png";
    constexpr char DEFORMED_HUMAN[] = "deformed_human.png";
    constexpr char FIRE_GIANT[] = "fire_giant.png";
    constexpr char OGRE[] = "ogre.png";
    constexpr char SIREN[] = "siren.png";
    constexpr char MERFOLK_IMPALER_WATER[] = "merfolk_impaler_water.png";
    constexpr char KOBOLD[] = "kobold.png";
    constexpr char SHAPESHIFTER[] = "shapeshifter.png";
    constexpr char HYDRA4[] = "hydra4.png";
    constexpr char OOZE[] = "ooze.png";
    constexpr char LINDWURM[] = "lindwurm.png";
    constexpr char JELLY[] = "jelly.png";
    constexpr char EYE_OF_DEVASTATION[] = "eye_of_devastation.png";
    constexpr char DAEVA[] = "daeva.png";
    constexpr char DEEP_TROLL[] = "deep_troll.png";
    constexpr char MERFOLK_JAVELINEER[] = "merfolk_javelineer.png";
    constexpr char MERFOLK_AQUAMANCER_WATER[] = "merfolk_aquamancer_water.png";
    constexpr char STEAM_DRAGON[] = "steam_dragon.png";
    constexpr char ORC_KNIGHT[] = "orc_knight.png";
    constexpr char SHADOW_DRAGON[] = "shadow_dragon.png";
    constexpr char IRON_TROLL_MONK_GHOST[] = "iron_troll_monk_ghost.png";
    namespace demons {
      constexpr char UGLY_THING5[] = "ugly_thing5.png";
      constexpr char UGLY_THING3[] = "ugly_thing3.png";
      constexpr char UNSEEN_HORROR[] = "unseen_horror.png";
      constexpr char VERY_UGLY_THING5[] = "very_ugly_thing5.png";
      constexpr char LOROCYPROCA[] = "lorocyproca.png";
      constexpr char ABOMINATION_LARGE[] = "abomination_large.png";
      constexpr char RED_DEVIL[] = "red_devil.png";
      constexpr char LEMURE[] = "lemure.png";
      constexpr char HAIRY_DEVIL[] = "hairy_devil.png";
      constexpr char IRON_DEVIL[] = "iron_devil.png";
      constexpr char ABOMINATION_LARGE2[] = "abomination_large2.png";
      constexpr char ABOMINATION_LARGE1[] = "abomination_large1.png";
      constexpr char IRON_IMP[] = "iron_imp.png";
      constexpr char ABOMINATION_LARGE6[] = "abomination_large6.png";
      constexpr char ABOMINATION_LARGE5[] = "abomination_large5.png";
      constexpr char ABOMINATION_LARGE3[] = "abomination_large3.png";
      constexpr char TORMENTOR[] = "tormentor.png";
      constexpr char EFREET[] = "efreet.png";
      constexpr char WHITE_IMP[] = "white_imp.png";
      constexpr char BALRUG[] = "balrug.png";
      constexpr char IMP[] = "imp.png";
      constexpr char ICE_DEVIL[] = "ice_devil.png";
      constexpr char UGLY_THING1[] = "ugly_thing1.png";
      constexpr char ICE_FIEND[] = "ice_fiend.png";
      constexpr char NEQOXEC[] = "neqoxec.png";
      constexpr char ROTTING_DEVIL[] = "rotting_devil.png";
      constexpr char DEMONIC_CRAWLER[] = "demonic_crawler.png";
      constexpr char CHAOS_SPAWN[] = "chaos_spawn.png";
      constexpr char SOUL_EATER[] = "soul_eater.png";
      constexpr char PIT_FIEND[] = "pit_fiend.png";
      constexpr char VERY_UGLY_THING3[] = "very_ugly_thing3.png";
      constexpr char SHADOW_IMP[] = "shadow_imp.png";
      constexpr char MIDGE[] = "midge.png";
      constexpr char CIGOTUVIS_MONSTER[] = "cigotuvis_monster.png";
      constexpr char BEAST[] = "beast.png";
      constexpr char GREEN_DEATH[] = "green_death.png";
      constexpr char HELLION[] = "hellion.png";
      constexpr char ABOMINATION_LARGE4[] = "abomination_large4.png";
      constexpr char ABOMINATION_SMALL[] = "abomination_small.png";
      constexpr char SHADOW_DEMON[] = "shadow_demon.png";
      constexpr char SMOKE_DEMON[] = "smoke_demon.png";
      constexpr char UGLY_THING4[] = "ugly_thing4.png";
      constexpr char TENTACLED_MONSTROSITY[] = "tentacled_monstrosity.png";
      constexpr char CACODEMON[] = "cacodemon.png";
      constexpr char SIXFIRHY[] = "sixfirhy.png";
      constexpr char QUASIT[] = "quasit.png";
      constexpr char SHADOW_FIEND[] = "shadow_fiend.png";
      constexpr char HELLWING[] = "hellwing.png";
      constexpr char VERY_UGLY_THING1[] = "very_ugly_thing1.png";
      constexpr char UGLY_THING2[] = "ugly_thing2.png";
      constexpr char FIEND[] = "fiend.png";
      constexpr char VERY_UGLY_THING4[] = "very_ugly_thing4.png";
      constexpr char BLUE_DEATH[] = "blue_death.png";
      constexpr char EXECUTIONER[] = "executioner.png";
      constexpr char VERY_UGLY_THING[] = "very_ugly_thing.png";
      constexpr char UFETUBUS[] = "ufetubus.png";
      constexpr char RAKSHASA[] = "rakshasa.png";
      constexpr char BLUE_DEVIL[] = "blue_devil.png";
      constexpr char YNOXINUL[] = "ynoxinul.png";
      constexpr char REAPER[] = "reaper.png";
      constexpr char UGLY_THING[] = "ugly_thing.png";
      constexpr char VERY_UGLY_THING2[] = "very_ugly_thing2.png";
      constexpr char SUN_DEMON[] = "sun_demon.png";
      constexpr char ORANGE_DEMON[] = "orange_demon.png";
    }  // namespace demons
    constexpr char ORC_WIZARD[] = "orc_wizard.png";
    constexpr char TWO_HEADED_OGRE[] = "two_headed_ogre.png";
    constexpr char AZURE_JELLY[] = "azure_jelly.png";
    constexpr char MERMAID[] = "mermaid.png";
    constexpr char NECROMANCER[] = "necromancer.png";
    constexpr char EYE_OF_DRAINING[] = "eye_of_draining.png";
    constexpr char ORC_PRIEST[] = "orc_priest.png";
    constexpr char DEFORMED_ORC[] = "deformed_orc.png";
    constexpr char GIANT_AMOEBA[] = "giant_amoeba.png";
    constexpr char NAGA_MAGE[] = "naga_mage.png";
    constexpr char DEEP_ELF_PRIEST[] = "deep_elf_priest.png";
    constexpr char DEFORMED_ELF[] = "deformed_elf.png";
    namespace unique {
      constexpr char TIAMAT[] = "tiamat.png";
      constexpr char FRANCES[] = "frances.png";
      constexpr char AIZUL[] = "aizul.png";
      constexpr char SIGMUND[] = "sigmund.png";
      constexpr char NORBERT[] = "norbert.png";
      constexpr char PRINCE_RIBBIT[] = "prince_ribbit.png";
      constexpr char LERNAEAN_HYDRA[] = "lernaean_hydra.png";
      constexpr char ILSUIW_WATER[] = "ilsuiw_water.png";
      constexpr char MURRAY[] = "murray.png";
      constexpr char MARGERY[] = "margery.png";
      constexpr char BLORK_THE_ORC[] = "blork_the_orc.png";
      constexpr char WIGLAF[] = "wiglaf.png";
      constexpr char IJYB[] = "ijyb.png";
      constexpr char NERGALLE[] = "nergalle.png";
      constexpr char GRINDER_CLEAVER[] = "grinder_cleaver.png";
      constexpr char CEREBOV[] = "cerebov.png";
      constexpr char CRAZY_YIUF[] = "crazy_yiuf.png";
      constexpr char GRUM[] = "grum.png";
      constexpr char ROYAL_JELLY[] = "royal_jelly.png";
      constexpr char SAINT_ROKA[] = "saint_roka.png";
      constexpr char MARA[] = "mara.png";
      constexpr char URUG[] = "urug.png";
      constexpr char EROLCHA[] = "erolcha.png";
      constexpr char MAURICE[] = "maurice.png";
      constexpr char XTAHUA[] = "xtahua.png";
      constexpr char DUANE[] = "duane.png";
      constexpr char GRINDER[] = "grinder.png";
      constexpr char PURGY[] = "purgy.png";
      constexpr char MNOLEG[] = "mnoleg.png";
      constexpr char AZRAEL[] = "azrael.png";
      constexpr char ANTAEUS[] = "antaeus.png";
      constexpr char HAROLD[] = "harold.png";
      constexpr char SERPENT_OF_HELL[] = "serpent_of_hell.png";
      constexpr char LOUISE[] = "louise.png";
      constexpr char NORRIS[] = "norris.png";
      constexpr char POLYPHEMUS[] = "polyphemus.png";
      constexpr char ROXANNE[] = "roxanne.png";
      constexpr char FREDERICK[] = "frederick.png";
      constexpr char GERYON[] = "geryon.png";
      constexpr char ERESHKIGAL[] = "ereshkigal.png";
      constexpr char DISSOLUTION[] = "dissolution.png";
      constexpr char AGNES[] = "agnes.png";
      constexpr char SONJA[] = "sonja.png";
      constexpr char MAUD[] = "maud.png";
      constexpr char ILSUIW[] = "ilsuiw.png";
      constexpr char SNORG[] = "snorg.png";
      constexpr char BORIS[] = "boris.png";
      constexpr char JOSEPH[] = "joseph.png";
      constexpr char JESSICA[] = "jessica.png";
      constexpr char GASTRONOK[] = "gastronok.png";
      constexpr char JOSEPHINE[] = "josephine.png";
      constexpr char DISPATER[] = "dispater.png";
      constexpr char KIRKE[] = "kirke.png";
      constexpr char FRANCIS[] = "francis.png";
      constexpr char ENCHANTRESS[] = "enchantress.png";
      constexpr char TERENCE[] = "terence.png";
      constexpr char RUPERT[] = "rupert.png";
      constexpr char LOM_LOBON[] = "lom_lobon.png";
      constexpr char ASMODEUS[] = "asmodeus.png";
      constexpr char MENKAURE[] = "menkaure.png";
      constexpr char PSYCHE[] = "psyche.png";
      constexpr char JOZEF[] = "jozef.png";
      constexpr char EUSTACHIO[] = "eustachio.png";
      constexpr char ERICA[] = "erica.png";
      constexpr char GLOORX_VLOQ[] = "gloorx_vloq.png";
      constexpr char NESSOS[] = "nessos.png";
      constexpr char DONALD[] = "donald.png";
      constexpr char EDMUND[] = "edmund.png";
      constexpr char NELLIE[] = "nellie.png";
    }  // namespace unique
    constexpr char STORM_DRAGON[] = "storm_dragon.png";
    constexpr char YAKTAUR_CAPTAIN_MELEE[] = "yaktaur_captain-melee.png";
    constexpr char MERFOLK_AQUAMANCER[] = "merfolk_aquamancer.png";
    constexpr char GIANT_ORANGE_BRAIN[] = "giant_orange_brain.png";
    constexpr char KOBOLD_DEMONOLOGIST[] = "kobold_demonologist.png";
    constexpr char STONE_GIANT[] = "stone_giant.png";
    constexpr char HYDRA1[] = "hydra1.png";
    constexpr char SPHINX[] = "sphinx.png";
    constexpr char DEEP_ELF_FIGHTER[] = "deep_elf_fighter.png";
    constexpr char MOTTLED_DRAGON[] = "mottled_dragon.png";
    constexpr char ELF[] = "elf.png";
    constexpr char MANTICORE[] = "manticore.png";
    constexpr char SWAMP_DRAGON[] = "swamp_dragon.png";
    constexpr char NAGA[] = "naga.png";
    constexpr char HYDRA5[] = "hydra5.png";
    constexpr char CYCLOPS[] = "cyclops.png";
    constexpr char HOBGOBLIN[] = "hobgoblin.png";
    constexpr char CENTAUR[] = "centaur.png";
    constexpr char MERFOLK_JAVELINEER_WATER[] = "merfolk_javelineer_water.png";
    constexpr char GOBLIN[] = "goblin.png";
    constexpr char HILL_GIANT[] = "hill_giant.png";
    constexpr char IRON_TROLL[] = "iron_troll.png";
    constexpr char HUMAN_SLAVE[] = "human_slave.png";
    constexpr char DEEP_ELF_MAGE[] = "deep_elf_mage.png";
    constexpr char GOLDEN_DRAGON[] = "golden_dragon.png";
    constexpr char SIREN_WATER[] = "siren_water.png";
    constexpr char MINOTAUR[] = "minotaur.png";
    constexpr char DEEP_ELF_BLADEMASTER[] = "deep_elf_blademaster.png";
    constexpr char ANGEL[] = "angel.png";
    constexpr char HARPY[] = "harpy.png";
    constexpr char FROST_GIANT[] = "frost_giant.png";
    constexpr char ORC_HIGH_PRIEST[] = "orc_high_priest.png";
    constexpr char ORC_WARRIOR[] = "orc_warrior.png";
    constexpr char HYDRA3[] = "hydra3.png";
    constexpr char FIRE_DRAKE[] = "fire_drake.png";
    constexpr char ACID_BLOB[] = "acid_blob.png";
    constexpr char SWAMP_DRAKE[] = "swamp_drake.png";
    constexpr char BIG_KOBOLD[] = "big_kobold.png";
    constexpr char BROWN_OOZE[] = "brown_ooze.png";
    constexpr char WIZARD[] = "wizard.png";
    constexpr char DEEP_ELF_CONJURER[] = "deep_elf_conjurer.png";
    constexpr char ORC_WARLORD[] = "orc_warlord.png";
    constexpr char ICE_DRAGON[] = "ice_dragon.png";
    constexpr char HALFLING[] = "halfling.png";
    constexpr char DEEP_ELF_SUMMONER[] = "deep_elf_summoner.png";
    constexpr char QUICKSILVER_DRAGON[] = "quicksilver_dragon.png";
    constexpr char GREAT_ORB_OF_EYES[] = "great_orb_of_eyes.png";
    constexpr char GUARDIAN_SERPENT[] = "guardian_serpent.png";
    constexpr char ROCK_TROLL[] = "rock_troll.png";
    constexpr char YAKTAUR_MELEE[] = "yaktaur-melee.png";
    constexpr char GRIFFON[] = "griffon.png";
    constexpr char OGRE_MAGE[] = "ogre_mage.png";
    constexpr char ORC[] = "orc.png";
    constexpr char DEEP_ELF_DEATH_MAGE[] = "deep_elf_death_mage.png";
    constexpr char PULSATING_LUMP[] = "pulsating_lump.png";
    constexpr char HUMAN_MONK_GHOST[] = "human_monk_ghost.png";
    constexpr char GREATER_NAGA[] = "greater_naga.png";
    constexpr char GOLDEN_EYE[] = "golden_eye.png";
    constexpr char MERFOLK_PLAIN[] = "merfolk_plain.png";
    constexpr char SHINING_EYE[] = "shining_eye.png";
    constexpr char GNOLL[] = "gnoll.png";
    constexpr char DEEP_ELF_SORCERER[] = "deep_elf_sorcerer.png";
    constexpr char DEEP_ELF_MASTER_ARCHER[] = "deep_elf_master_archer.png";
    constexpr char VAULT_GUARD[] = "vault_guard.png";
    constexpr char MERFOLK_FIGHTER[] = "merfolk_fighter.png";
    constexpr char WYVERN[] = "wyvern.png";
    constexpr char CENTAUR_MELEE[] = "centaur-melee.png";
    constexpr char DEATH_DRAKE[] = "death_drake.png";
    constexpr char DRAGON[] = "dragon.png";
    constexpr char ORB_GUARDIAN[] = "orb_guardian.png";
    constexpr char CENTAUR_WARRIOR_MELEE[] = "centaur_warrior-melee.png";
    constexpr char GIANT_EYEBALL[] = "giant_eyeball.png";
    constexpr char TROLL[] = "troll.png";
    constexpr char GLOWING_SHAPESHIFTER[] = "glowing_shapeshifter.png";
    constexpr char YAKTAUR[] = "yaktaur.png";
    constexpr char DWARF[] = "dwarf.png";
    constexpr char MERFOLK_IMPALER[] = "merfolk_impaler.png";
  }  // namespace monsters
  namespace player {}
  namespace other {
    constexpr char TRANSPARENT[] = "transparent.png";
  }
  namespace items {
    namespace books {
      constexpr char DARK_GRAY[] = "dark_gray.png";
      constexpr char DARK_BLUE[] = "dark_blue.png";
      constexpr char DARK_BROWN[] = "dark_brown.png";
    }  // namespace books
    namespace boots {
      constexpr char BOOTS4_GREEN[] = "boots4_green.png";
      constexpr char BOOTS1_BROWN[] = "boots1_brown.png";
      constexpr char BOOTS2_JACKBOOTS[] = "boots2_jackboots.png";
      constexpr char BOOTS3_STRIPE[] = "boots3_stripe.png";
    }  // namespace boots
    namespace armour {
      constexpr char CLOAK3[] = "cloak3.png";
      constexpr char CLOAK2[] = "cloak2.png";
    }  // namespace armour
    namespace weapon {
      constexpr char GREATSWORD2[] = "greatsword2.png";
      constexpr char CLUB[] = "club.png";
      constexpr char BROAD_AXE2[] = "broad_axe2.png";
      constexpr char GREATSWORD1[] = "greatsword1.png";
      constexpr char BROAD_AXE3[] = "broad_axe3.png";
      constexpr char BULLWHIP[] = "bullwhip.png";
      constexpr char DAGGER[] = "dagger.png";
    }  // namespace weapon
    namespace helmets {
      constexpr char WIZARD_HAT1[] = "wizard_hat1.png";
      constexpr char ELVEN_LEATHER_HELM[] = "elven_leather_helm.png";
      constexpr char HELMET4_VISOR[] = "helmet4_visor.png";
      constexpr char HELMET2_ETCHED[] = "helmet2_etched.png";
      constexpr char HELMET1_VISORED[] = "helmet1_visored.png";
      constexpr char HELMET3[] = "helmet3.png";
      constexpr char WIZARD_HAT2[] = "wizard_hat2.png";
    }  // namespace helmets
    namespace food {
      constexpr char BANANA[] = "banana.png";
      constexpr char BEEF_JERKY[] = "beef_jerky.png";
      constexpr char APRICOT[] = "apricot.png";
    }  // namespace food
  }    // namespace items
}  // namespace image
