#pragma once

// File generated by the gen_img.py script

namespace Item {
constexpr char TRANSPARENT[] = "transparent.png";
constexpr char DARK_GRAY[] = "dark_gray.png";
constexpr char DARK_BLUE[] = "dark_blue.png";
constexpr char DARK_BROWN[] = "dark_brown.png";
constexpr char CLOAK3[] = "cloak3.png";
constexpr char CLOAK2[] = "cloak2.png";
constexpr char GREATSWORD2[] = "greatsword2.png";
constexpr char CLUB[] = "club.png";
constexpr char BROAD_AXE2[] = "broad_axe2.png";
constexpr char GREATSWORD1[] = "greatsword1.png";
constexpr char BROAD_AXE3[] = "broad_axe3.png";
constexpr char BULLWHIP[] = "bullwhip.png";
constexpr char DAGGER[] = "dagger.png";
constexpr char BANANA[] = "banana.png";
constexpr char BEEF_JERKY[] = "beef_jerky.png";
constexpr char APRICOT[] = "apricot.png";
}  // namespace Item
