#pragma once

// File generated by the gen_img.py script

namespace image {
  namespace player {}
  namespace other {
    constexpr char TRANSPARENT[] = "transparent.png";
  }
  namespace items {
    namespace books {
      constexpr char DARK_GRAY[] = "dark_gray.png";
      constexpr char DARK_BLUE[] = "dark_blue.png";
      constexpr char DARK_BROWN[] = "dark_brown.png";
    }  // namespace books
    namespace boots {
      constexpr char BOOTS4_GREEN[] = "boots4_green.png";
      constexpr char BOOTS1_BROWN[] = "boots1_brown.png";
      constexpr char BOOTS2_JACKBOOTS[] = "boots2_jackboots.png";
      constexpr char BOOTS3_STRIPE[] = "boots3_stripe.png";
    }  // namespace boots
    namespace armour {
      constexpr char CLOAK3[] = "cloak3.png";
      constexpr char CLOAK2[] = "cloak2.png";
    }  // namespace armour
    namespace weapon {
      constexpr char GREATSWORD2[] = "greatsword2.png";
      constexpr char CLUB[] = "club.png";
      constexpr char BROAD_AXE2[] = "broad_axe2.png";
      constexpr char GREATSWORD1[] = "greatsword1.png";
      constexpr char BROAD_AXE3[] = "broad_axe3.png";
      constexpr char BULLWHIP[] = "bullwhip.png";
      constexpr char DAGGER[] = "dagger.png";
    }  // namespace weapon
    namespace helmets {
      constexpr char WIZARD_HAT1[] = "wizard_hat1.png";
      constexpr char ELVEN_LEATHER_HELM[] = "elven_leather_helm.png";
      constexpr char HELMET4_VISOR[] = "helmet4_visor.png";
      constexpr char HELMET2_ETCHED[] = "helmet2_etched.png";
      constexpr char HELMET1_VISORED[] = "helmet1_visored.png";
      constexpr char HELMET3[] = "helmet3.png";
      constexpr char WIZARD_HAT2[] = "wizard_hat2.png";
    }  // namespace helmets
    namespace food {
      constexpr char BANANA[] = "banana.png";
      constexpr char BEEF_JERKY[] = "beef_jerky.png";
      constexpr char APRICOT[] = "apricot.png";
    }  // namespace food
  }  // namespace items
}  // namespace image
